platform :ios, '10.0'
use_frameworks!

def develop_pods
  # 提示组件框架
  pod 'SVProgressHUD', '~> 2.2.2'
  # 网络请求框架
  pod 'YTKNetwork', '~> 2.0.3'
  # AOP面向切面
  pod 'Aspects', '~> 1.4.1'
  # 响应函数式框架
  pod 'ReactiveObjC', '~> 3.0.0'
  # 路由组件化解耦
  pod 'JLRoutes', '~> 2.0.5'
  # 自动布局
  pod 'Masonry', '~> 1.0.2'
  # 刷新控件
  pod 'MJRefresh'
  # JSON转类
  pod 'YYModel'
  # 无数据底图
  pod 'LYEmptyView'
end

target 'XYBaseMVVM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WisdomPower
  develop_pods

end



